heat_template_version: 2015-10-15
description: Launch a basic instance with CirrOS image using the
             ``m1.tiny`` flavor, ``mykey`` key,  and one network.

parameters:

resources:
  server:
    type: OS::Nova::Server
    properties:
      flavor: m1.nano
      key_name: mykey
      networks:
      - network: 91fa4913-5ca5-4bfb-a9b3-3481f73c6137
      block_device_mapping_v2: [{"volume_size": 1, "delete_on_termination": True, device_name: "/dev/vda", "image": "cirros"}]
outputs:
  instance_name:
    description: Name of the instance.
    value: { get_attr: [ server, name ] }
  instance_ip:
    description: IP address of the instance.
    value: { get_attr: [ server, first_address ] }
